global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "apigateway"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8093"]

  - job_name: "config-server"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["config-server:8890"]

  - job_name: "eureka"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["eureka:8761"]

  - job_name: "users"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["users:8087"]

  - job_name: "courses"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["courses:8086"]

  - job_name: "forum"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["forum:8096"]

  - job_name: "messaging"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["messaging:8092"]

  - job_name: "adaptive-learning"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["adaptive-learning:8094"]

  - job_name: "ai-assistant-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ai-assistant:8095"]
